### PR TITLE
feat(unit-tests): add unit test cases for components, actions and pag…

### PR DESCRIPTION
**Pull request by FloPetra**
- I highly recommend trying to not use any type as this has caused a lot of issues in tests
- I didn't write test for pages and routes in this PR

Screenshot 2023-10-06 at 14 18 39

### CODE REVIEW

**Comment by DylanP97** [comment]
Thank you. I'll check and get back to you soon

**Comment by DylanP97** [comment]
Hi there,

1 - First off, there are changes I didn't requested. I only asked for creating tests.

2 - You should not edit the package-lock.json file. Sorry but he should be ignored when committing.

3 - Thanks for all the formatting, it looks great and clean.

4 - I didn't experiment the tests suits you made, because within the last days I've been changing and committing some code on this project master branch, especially with removing the const router = `useRouter()` from the components and using the `<Link> next/link` instead.

5 - Within the api routes, you added return null for error response, but this approach is not working on production deployment so I think you should let it as it was.

6 - I suggest you make the changes I said and then make a pull request but not for the main branch

**Review by DylanP97 — COMMENTED** [review]
alright

**Comment by FloPetra** [comment]
Hi, I'd closed the PR because I thought you wanted it for another branch. I've synced the repo and I've been working on the failing tests because of new changes, as well as on your comments.

Would you like me to create another PR?

**Comment by DylanP97** [comment]
Yes that would be great

**Comment by DylanP97** [comment]
> * I highly recommend trying to not use any type as this has caused a lot of issues in tests
> * I didn't write test for pages and routes in this PR
> 
> Screenshot 2023-10-06 at 14 18 39

Yes I need to changes the any types

**Pull request merged**
